/**
 * @file pgr.cpp
 * @brief Implementation of OpenGL utility functions.
 */

#include "lib.h"

// Define STB_IMAGE_IMPLEMENTATION in exactly one source file
#define STB_IMAGE_IMPLEMENTATION
#include <stb_image.h>

namespace pgr {

    bool initialize(int major, int minor) {
        // Initialize GLEW
        glewExperimental = GL_TRUE;
        GLenum err = glewInit();

        if (err != GLEW_OK) {
            std::cerr << "GLEW initialization failed: " << glewGetErrorString(err) << std::endl;
            return false;
        }

        // Clear any OpenGL errors generated by GLEW initialization
        while (glGetError() != GL_NO_ERROR) {}

        // Check OpenGL version
        const char* versionStr = (const char*)glGetString(GL_VERSION);
        if (versionStr) {
            std::cout << "OpenGL version: " << versionStr << std::endl;
        }

        // Parse version
        int actualMajor = 0, actualMinor = 0;
        if (versionStr) {
            sscanf(versionStr, "%d.%d", &actualMajor, &actualMinor);
        }

        if (actualMajor < major || (actualMajor == major && actualMinor < minor)) {
            std::cerr << "Required OpenGL " << major << "." << minor
                      << " but got " << actualMajor << "." << actualMinor << std::endl;
            return false;
        }

        std::cout << "GLEW initialized successfully" << std::endl;
        std::cout << "GLEW version: " << glewGetString(GLEW_VERSION) << std::endl;
        std::cout << "OpenGL Renderer: " << glGetString(GL_RENDERER) << std::endl;
        std::cout << "OpenGL Vendor: " << glGetString(GL_VENDOR) << std::endl;

        return true;
    }

    void dieWithError(const std::string& message) {
        std::cerr << "FATAL ERROR: " << message << std::endl;
        exit(EXIT_FAILURE);
    }

    void checkGLError(const char* file, int line) {
        GLenum err;
        while ((err = glGetError()) != GL_NO_ERROR) {
            std::string errorStr;
            switch (err) {
                case GL_INVALID_ENUM:      errorStr = "GL_INVALID_ENUM"; break;
                case GL_INVALID_VALUE:     errorStr = "GL_INVALID_VALUE"; break;
                case GL_INVALID_OPERATION: errorStr = "GL_INVALID_OPERATION"; break;
                case GL_STACK_OVERFLOW:    errorStr = "GL_STACK_OVERFLOW"; break;
                case GL_STACK_UNDERFLOW:   errorStr = "GL_STACK_UNDERFLOW"; break;
                case GL_OUT_OF_MEMORY:     errorStr = "GL_OUT_OF_MEMORY"; break;
                case GL_INVALID_FRAMEBUFFER_OPERATION: errorStr = "GL_INVALID_FRAMEBUFFER_OPERATION"; break;
                default:                   errorStr = "Unknown error"; break;
            }
            std::cerr << "OpenGL error " << errorStr << " (" << err << ") at "
                      << file << ":" << line << std::endl;
        }
    }

    std::string readFile(const std::string& filename) {
        std::ifstream file(filename);
        if (!file.is_open()) {
            std::cerr << "Failed to open file: " << filename << std::endl;
            return "";
        }

        std::stringstream buffer;
        buffer << file.rdbuf();
        return buffer.str();
    }

    GLuint createShaderFromSource(GLenum shaderType, const std::string& source) {
        GLuint shader = glCreateShader(shaderType);

        const char* sourcePtr = source.c_str();
        glShaderSource(shader, 1, &sourcePtr, nullptr);
        glCompileShader(shader);

        // Check compilation status
        GLint success;
        glGetShaderiv(shader, GL_COMPILE_STATUS, &success);

        if (!success) {
            GLint logLength;
            glGetShaderiv(shader, GL_INFO_LOG_LENGTH, &logLength);

            std::vector<char> log(logLength);
            glGetShaderInfoLog(shader, logLength, nullptr, log.data());

            std::string shaderTypeStr;
            switch (shaderType) {
                case GL_VERTEX_SHADER:   shaderTypeStr = "vertex"; break;
                case GL_FRAGMENT_SHADER: shaderTypeStr = "fragment"; break;
                case GL_GEOMETRY_SHADER: shaderTypeStr = "geometry"; break;
                default:                 shaderTypeStr = "unknown"; break;
            }

            std::cerr << "Shader compilation failed (" << shaderTypeStr << "):\n"
                      << log.data() << std::endl;

            glDeleteShader(shader);
            return 0;
        }

        return shader;
    }

    GLuint createShaderFromFile(GLenum shaderType, const std::string& filename) {
        std::string source = readFile(filename);
        if (source.empty()) {
            std::cerr << "Failed to read shader file: " << filename << std::endl;
            return 0;
        }

        GLuint shader = createShaderFromSource(shaderType, source);
        if (shader == 0) {
            std::cerr << "Failed to compile shader from file: " << filename << std::endl;
        }

        return shader;
    }

    GLuint createProgram(const std::vector<GLuint>& shaders) {
        GLuint program = glCreateProgram();

        // Attach all shaders
        for (GLuint shader : shaders) {
            if (shader != 0) {
                glAttachShader(program, shader);
            }
        }

        // Link the program
        glLinkProgram(program);

        // Check link status
        GLint success;
        glGetProgramiv(program, GL_LINK_STATUS, &success);

        if (!success) {
            GLint logLength;
            glGetProgramiv(program, GL_INFO_LOG_LENGTH, &logLength);

            std::vector<char> log(logLength);
            glGetProgramInfoLog(program, logLength, nullptr, log.data());

            std::cerr << "Program linking failed:\n" << log.data() << std::endl;

            glDeleteProgram(program);
            return 0;
        }

        return program;
    }

    void deleteProgramAndShaders(GLuint program) {
        if (program == 0) return;

        // Get attached shaders
        GLint numShaders;
        glGetProgramiv(program, GL_ATTACHED_SHADERS, &numShaders);

        if (numShaders > 0) {
            std::vector<GLuint> shaders(numShaders);
            glGetAttachedShaders(program, numShaders, nullptr, shaders.data());

            // Detach and delete each shader
            for (GLuint shader : shaders) {
                glDetachShader(program, shader);
                glDeleteShader(shader);
            }
        }

        glDeleteProgram(program);
    }

    GLuint createTexture(const std::string& filename) {
        // Load image using stb_image
        int width, height, channels;
        stbi_set_flip_vertically_on_load(true);
        unsigned char* data = stbi_load(filename.c_str(), &width, &height, &channels, 0);

        if (!data) {
            std::cerr << "Failed to load texture: " << filename << std::endl;
            std::cerr << "STB Error: " << stbi_failure_reason() << std::endl;
            return 0;
        }

        // Determine format based on channels
        GLenum format;
        GLenum internalFormat;
        switch (channels) {
            case 1:
                format = GL_RED;
                internalFormat = GL_RED;
                break;
            case 2:
                format = GL_RG;
                internalFormat = GL_RG;
                break;
            case 3:
                format = GL_RGB;
                internalFormat = GL_RGB;
                break;
            case 4:
                format = GL_RGBA;
                internalFormat = GL_RGBA;
                break;
            default:
                std::cerr << "Unknown number of channels: " << channels << std::endl;
                stbi_image_free(data);
                return 0;
        }

        // Create OpenGL texture
        GLuint textureID;
        glGenTextures(1, &textureID);
        glBindTexture(GL_TEXTURE_2D, textureID);

        // Set texture parameters
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR_MIPMAP_LINEAR);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);

        // Upload texture data
        glTexImage2D(GL_TEXTURE_2D, 0, internalFormat, width, height, 0, format, GL_UNSIGNED_BYTE, data);
        glGenerateMipmap(GL_TEXTURE_2D);

        glBindTexture(GL_TEXTURE_2D, 0);
        stbi_image_free(data);

        std::cout << "Loaded texture: " << filename << " (" << width << "x" << height
                  << ", " << channels << " channels)" << std::endl;

        return textureID;
    }

    bool loadTexImage2D(const std::string& filename, GLenum target) {
        // Load image (don't flip for cubemaps)
        int width, height, channels;

        // Don't flip vertically for cubemap faces
        bool isCubemapFace = (target >= GL_TEXTURE_CUBE_MAP_POSITIVE_X &&
                              target <= GL_TEXTURE_CUBE_MAP_NEGATIVE_Z);
        stbi_set_flip_vertically_on_load(!isCubemapFace);

        unsigned char* data = stbi_load(filename.c_str(), &width, &height, &channels, 0);

        if (!data) {
            std::cerr << "Failed to load texture: " << filename << std::endl;
            std::cerr << "STB Error: " << stbi_failure_reason() << std::endl;
            return false;
        }

        // Determine format
        GLenum format;
        switch (channels) {
            case 1: format = GL_RED; break;
            case 2: format = GL_RG; break;
            case 3: format = GL_RGB; break;
            case 4: format = GL_RGBA; break;
            default:
                std::cerr << "Unknown number of channels: " << channels << std::endl;
                stbi_image_free(data);
                return false;
        }

        // Upload texture data
        glTexImage2D(target, 0, format, width, height, 0, format, GL_UNSIGNED_BYTE, data);

        stbi_image_free(data);
        return true;
    }

} // namespace pgr